### ISSUE TITLE
Exception on CheckBan

### ISSUE THREAD

**Issue by Nerus87** [JoinedSenses/SM-SuperSprayHandler#4]
> L 01/11/2020 - 21:55:04: [SM] Blaming: supersprayhandler.smx
L 01/11/2020 - 21:55:04: [SM] Call stack trace:
L 01/11/2020 - 21:55:04: [SM]   [0] SQL_LockDatabase
L 01/11/2020 - 21:55:04: [SM]   [1] Line 587, supersprayhandler.sp::CheckBan
L 01/11/2020 - 21:55:04: [SM]   [2] Line 233, supersprayhandler.sp::OnClientPutInServer
L 01/11/2020 - 21:55:04: [SM] Exception reported: Invalid database Handle 0 (error: 4)

**Comment by JoinedSenses** [comment]
Should be fixed.
